### ISSUE TITLE
faulty_device_run.rb and idempotent_device_run.rb

### ISSUE THREAD

**Issue by philomory** [Lavaburn/puppet-mikrotik#1]
I'm interested in playing around with this system, and am trying to get the test harness up and running, but the test suite requires `faulty_device_run.rb` and `idempotent_device_run.rb`, which are not in the repo because they are .gitignored. I'm assuming they're ignored because they contain local-environment-specific information, but, any chance you could share a template of what they are supposed to look like so I can create my own?

**Comment by Lavaburn** [comment]
That must have been a mistake on my side. Those files do not contain anything special and should have been included, which is now the case.

I have updated the acceptance helper to allow local test config. See spec/fixtures/testnodes.example.yaml
